### PR TITLE
fix: no faulty host resolving

### LINKED ISSUE #14: segfault when using existing docker networks
When using an existing docker network with a Jaeger service named `jaeger`, calling any script causes the PHP process to segfault:

    $ bin/console
    Segmentation fault (core dumped)
    $

Further investigation showed, that [dns_get_record()](https://www.php.net/manual/en/function.dns-get-record.php) does not handle this situation well, but [gethostbyname()](https://www.php.net/manual/en/function.gethostbyname.php) does. Therefore, we should switch the implementation.

### PR DESCRIPTION
**Pull request by cawolf**
fixes auxmoney/OpentracingBundle-core#14

### CODE REVIEW

File: Factory/ZipkinTracerFactory.php [hunk 1]
```diff
@@ -30,12 +32,8 @@ public function create(string $projectName, string $agentHost, string $agentPort
     {
         $tracer = new NoopTracer();
 
-        if (!dns_get_record($agentHost) && !filter_var($agentHost, FILTER_VALIDATE_IP)) {
-            $this->logger->warning(self::class . ': could not resolve agent host "' . $agentHost . '"');
-            return $tracer;
-        }
-
         try {
+            $this->agentHostResolver->resolveAgentHost($agentHost);
```
Comment (cHeeSaW) [inline Factory/ZipkinTracerFactory.php]: hm, the Naming is maybe a little bit strange. While i saw the code in the core bundle it seamed obvious, but when reading it "in action" i would expect that there is a return valiue and something is done with the agenthost after resolving it... the `resolveAgentHost` function-name doesn't sound like a check, but it is?

**Review by cHeeSaW — DISMISSED** [review]

File: Factory/ZipkinTracerFactory.php (hunk 1 above)
Comment (cawolf) [reply Factory/ZipkinTracerFactory.php]: True, I will rename it to `ensureAgentHostIsResolvable()` to make it more obvious.

**Review by mmross — APPROVED** [review]
